#!/usr/bin/env bash
#Configure your domain zone.

print_domainzone (){
  dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}

if [ "$#" -eq ]
then
   print_domainzone "$2.$1" "$2"
else
   print_domainzone "www.$1" "www"
   print_domainzone "lb-01.$1" "lb-01"
   print_domainzone "web-01.$1" "web-01"
   print_domainzone "web-02.$1" "web-02"
fi
