#!/usr/bin/env bash
#Show domain zone and subdomain.

print_DomainSubdomain () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    print_DomainSubdomain "$2.$1" "$2"
else
    printDomainSubdomain "www.$1" "www"
    printDomainSubdomain "lb-01.$1" "lb-01"
    printDomainSubdomain "web-01.$1" "web-01"
    printDomainSubdomain "web-02.$1" "web-02"
fi
