#!/usr/bin/env bash

#Install nginx.
sudo apt-get update -y -qq
sudo apt-get install nginx -y

#Starting service nginx and nginx firewall.
sudo service nginx start
sudo ufw allow 'Nginx HTTP'

#Enable user to edit files.
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

#Default backup index.
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.back

#Creating default index.
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

#Restart nginx.
sudo service nginx restart
