#!/usr/bin/env bash

#Install nginx.
sudo apt-get update -y -qq
sudo apt-get install -y nginx

#Creating the /etc/nginx/html directory && empty index.html file.
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

#Setting the content of the index.html file to "Hello World!".
echo "Hello World!" > /etc/nginx/html/index.html

#Seting Nginx to listen on port 80 and serve files from the /etc/nginx/html directory.
printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

#Restart nginx.
sudo service nginx restart
