#!/usr/bin/env bash
# script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install & configure HAproxy.

sudo apt-get -y update
apt-get -y install haproxy

# edit config file

server_config=\
"
frontend  Muna_frontend
        bind *:80
        mode http
        default_backend Muna_backend
backend Muna_backend
        balance roundrobin
        server 512667-web-01 54.146.92.3:80 check
        server 512667-web-02 54.160.116.131:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
