#!/usr/bin/env bash
#Bash script that makes Nginx running as the nginx user and listening on all active IPs on port 8080.

#Set a user.
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

#Set pot 8080.
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

#Change owner permissions.
chmod 644 /etc/nginx/nginx.conf

#Kill apache IF it's running so that apache don't interfere with nginx.
pkill apache2

#Restart Nginx.
sudo -u nginx service nginx start
